### ISSUE TITLE
Lombok

### ISSUE THREAD

**Issue by ProfliX** [BetterPluginsSpigot/BetterYaml#9]
Start using [Lombok](https://projectlombok.org/) ? Good or bad? Further inspections are required.

**Comment by Nuytemans-Dieter** [comment]
We'll have to look into that, we don't have a lot of getters/setters so the benefits seem small (and sometimes work with `Optional`, which Lombok does not support). 
I don't know if it has support for creating constructors with optional parameters (similar to what we have now), but if it can, that would be nice addition.

**Comment by ProfliX** [comment]
> We'll have to look into that, we don't have a lot of getters/setters so the benefits seem small (and sometimes work with `Optional`, which Lombok does not support).
> I don't know if it has support for creating constructors with optional parameters (similar to what we have now), but if it can, that would be nice addition.

Well lombok is not just getters and setters, just check out all features.

**Comment by ProfliX** [comment]
> We'll have to look into that, we don't have a lot of getters/setters so the benefits seem small (and sometimes work with `Optional`, which Lombok does not support).
> I don't know if it has support for creating constructors with optional parameters (similar to what we have now), but if it can, that would be nice addition.

I will check it out.

**Comment by Nuytemans-Dieter** [comment]
> > We'll have to look into that, we don't have a lot of getters/setters so the benefits seem small (and sometimes work with `Optional`, which Lombok does not support).
> > I don't know if it has support for creating constructors with optional parameters (similar to what we have now), but if it can, that would be nice addition.
> 
> Well lombok is not just getters and setters, just check out all features.

It's definitely a nice tool, I'll have a more in-depth look later (I did just skim over their features).


> > We'll have to look into that, we don't have a lot of getters/setters so the benefits seem small (and sometimes work with `Optional`, which Lombok does not support).
> > I don't know if it has support for creating constructors with optional parameters (similar to what we have now), but if it can, that would be nice addition.
> 
> I will check it out.

Thank you!

**Comment by ProfliX** [comment]
> 
> 
> > > We'll have to look into that, we don't have a lot of getters/setters so the benefits seem small (and sometimes work with `Optional`, which Lombok does not support).
> > > I don't know if it has support for creating constructors with optional parameters (similar to what we have now), but if it can, that would be nice addition.
> > 
> > 
> > Well lombok is not just getters and setters, just check out all features.
> 
> It's definitely a nice tool, I'll have a more in-depth look later (I did just skim over their features).
> 
> > > We'll have to look into that, we don't have a lot of getters/setters so the benefits seem small (and sometimes work with `Optional`, which Lombok does not support).
> > > I don't know if it has support for creating constructors with optional parameters (similar to what we have now), but if it can, that would be nice addition.
> > 
> > 
> > I will check it out.
> 
> Thank you!

For now just using two thi
